name = "json_value_formatter"
version = "1.0.0"
description = "Format json_value values as JSON and Gleam source code."
licences = ["MIT"]
repository = { type = "github", user = "kwando", repo = "json_value_formatter" }
links = [{ title = "GitHub", href = "https://github.com/kwando/json_value_formatter" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
json_value = ">= 1.1.0 and < 2.0.0"
glam = ">= 2.0.4 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 2.0.2 and < 3.0.0"
simplifile = ">= 2.6.0 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
glance = ">= 7.0.0 and < 8.0.0"
